### PR TITLE
Toaster confirmation upon save

### PR DESCRIPTION
**Pull request by AjinkyaKaley**
Following file is changed:
- pages/admin/user-management/index.js

Functionality:
- Toaster pops up after saving the changes made to the table row

Note:
I was having some trouble with submitting the pull request, error message was "no difference due to unrelated history". I solved it by using this `allow-unrelated-histories` [solution](https://allaudin.github.io/git-unrelated-histories/). Please let me know if thats a correct approach to solve such kind of problem.
Also this is my first open source contribution, so please let me know if you have any feedback, i will be highly obliged.

Thanks

### CODE REVIEW

**Comment by ghost** [comment]
Hm, looks like this branch has a lot of extra file changes (33 in total). Seems like your merge into master didn't work quite right. I saw you had forked the repository, so it may be easiest to copy that index.js file you modified to a .txt on your machine just to be safe, then rebase your master onto mine. You can also simply create a new fork if you'd prefer.

**Comment by ghost** [comment]
Also @AjinkyaKaley, I'm about to transfer this repository to the parent organization I made this for. It's for our robotics club at Georgia Tech called Robojackets. Your Pull Request should still transfer over for review, just didn't want you to be confused by the ownership change.

**Comment by AjinkyaKaley** [comment]
Hi @Holben888 so I did rebase to get my fork upto date with yours, you can check this commita51e2ee9697b105065d0dd7e3e1604a05536b17d. 
However, additionally I had to add another commit on top of that. Please let me know if this works.

Also, I am fine with ownership change. Thanks for the heads up.

**Comment by ghost** [comment]
For future reference, you can track which files were changed on the top tab bar just below the PR title. Looks like it's at 36 differing files now. Fairly certain the issue is that I force pushed a change to master just after you created the fork, which erased a number of commits from the project. This was not a good judgement call on my part. To fix this, I now think the easiest solution would be for you to delete your current fork and create a new one, then copy over the index.js file you changed. Once you've done that and it looks functional, make a new pull request separate from this one. I'll close this PR out. 

Again, sorry for the confusion. Thanks again for contributing @AjinkyaKaley !

**Comment by ghost** [comment]
I would also recommend that in the future, instead of modifying the master on your fork, instead create a new branch within your fork to make changes. That way you can pull my master onto yours separately from your actual code modifications.

**Comment by AjinkyaKaley** [comment]
Hi @Holben888  apologies for that. As per your recommendation, I did create a new fork and submit my changes on that. Now the pull request is a lot cleaner. Thanks for the help.

**Pull request closed without merging**
