### PR TITLE
implemented toaster for role change on admin page

### PR DESCRIPTION
**Pull request by AjinkyaKaley**
Following files are changed:
- Package-lock.json
- pages/admin/user-management/index.js

Please let me know if you have any questions/concerns.

### CODE REVIEW

**Comment by ghost** [comment]
Changes look good! I request you undo your `package-lock.json` changes, since it looks like a lot of dependency versions were altered. Otherwise your changes to index.js look exactly like what we wanted.

**Comment by ghost** [comment]
Addresses #2

**Comment by AjinkyaKaley** [comment]
Hi @Holben888  Please check the last commit, I reverted the package-lock.json as per your request.

**Comment by ghost** [comment]
Thanks! Sorry about the Hound comments. They are autogenerated from a style checker we are now using in the project. Seems like it's using the default configuration, so I'm assuming your branch is a bit behind our master. Go ahead and merge the latest master @AjinkyaKaley. If anything Hound comments on is worth changing, I will let you know.

**Review by ghost — APPROVED** [review]
Resolved the styling conflicts raised by our checker. Also replaced your use of "function" with a newer JavaScript concept called arrow (=>) functions. When using arrow functions, JavaScript is smart enough to bind "this" to the context of whatever you're calling that function in. This means you don't have to assign "this" to a variable like you were doing before. There are a lot of little quirks like that in JS since the 2015 standards release that are definitely worth looking at.

Otherwise, looks good to merge. Thanks for bearing with me on this one!

**Comment by AjinkyaKaley** [comment]
Hi @Holben888 thank you so much for bearing with me as well. yes, javascript indeed is weird. This contribution gave me good head start for open source contribution. Thanks again :)

**Pull request merged**
